= Linkchecker API Guide v1
Test project;
:doctype: book
:toc:
:sectanchors:
:sectlinks:
:toclevels: 5
:source-highlighter: highlightjs

[[overview]]
= Обзор

*Linkchecker* - REST-сервис проверяющий работоспособность любой последовательности узлов, хранящихся в неориентированном ациклическом графе.

API REST-сервиса разбит на следующие категории:

* *GRAPH API* - набор команд позволяющий работать с графом в целом.
* *NODES API* - набор команд позволящий работать отдельно с вершинами графа.
* *EDGES API* - набор команд позволящий работать отдельно с рёбрами графа.

[[overview-common]]
== Общая информация

[[overview-http-verbs]]
=== HTTP методы

API Linkchecker следует стандартным соглашениям HTTP REST и поддерживает HTTP методы, перечисленные ниже.

|===
| Вид запроса | Назначание

| `GET`
| Используется для запроса содержимого указанного ресурса.

| `POST`
| Применяется для передачи пользовательских данных заданному ресурсу (создание нового ресурса или передача данных для обработки на стороне сервера).

| `DELETE`
| Удаляет указанный ресурс.

| `OPTIONS`
| Предоставляет информацию клиенту о доступных для работы HTTP методов.
|===

[[overview-http-status-codes]]
=== Коды состояния HTTP

В API Linkchecker используются следующие коды состояния HTTP.

|===
| Код состояния | Назначение

| `200 OK`
| успешный запрос. Если клиентом были запрошены какие-либо данные, то они находятся в заголовке и/или теле сообщения.

| `201 Created`
| В результате успешного выполнения запроса был создан новый ресурс.

| `204 No Content`
| сервер успешно обработал запрос, но в ответе были переданы только заголовки без тела сообщения.

| `422 Unprocessable Entity`
| сервер успешно принял запрос, может работать с указанным видом данных (например, в теле запроса находится XML-документ, имеющий верный синтаксис), однако имеется какая-то логическая ошибка, из-за которой невозможно произвести операцию над ресурсом

| `500 Internal Server Error`
| любая внутренняя ошибка сервера, которая не входит в рамки остальных ошибок класса.
|===

[[overview-http-errors]]
=== Ошибки

В случае возникновения ошибок во время работы REST-сервиса, клиенту будет возвращен структурированный набор данных в формате JSON

[source,json]
----
{
  "url": "request_link",
  "type": "APP_ERROR[,DATA_NOT_FOUND,DATA_ERROR,VALIDATION_ERROR, WRONG_REQUEST]",
  "place": "APP[,GRAPH,NODE,EDGE]",
  "messages": [
    "Any message 1",
    "Any message 2"
  ]
}
----

, где

* *url* - REST-запрос, при котором возникла ошибка
* *type* - тип ошибки
** _APP_ERROR_ - общие ошибки сервиса.
** _DATA_NOT_FOUND_ - ошибки, возникающие при поиске и извлечении данных.
** _DATA_ERROR_ - ошибки, возникающие при обработки данных.
** _VALIDATION_ERROR_ - ошибки, связанные с проверкой данных.
** _WRONG_REQUEST_ - ошибки, возникающие при некорректном запросе.
* *place* - места возникновения ошибок
** _APP_ - сервис
** _GRAPH_ - граф
** _NODE_ - вершины графа
** _EDGE_ - рёбра графа
* *messages* - сообщения об ошибках

Виды сообщения об ошибках:

*Обобщенные сообщения об ошибках*

* Argument must not be null - на вход вместо объекта был подан null
* Collection must not be empty - на вход поступила пустая коллекция данных
* Collection must not contain a null item - на вход поступила коллекция, в которой содержится null элемент
* Collection must have more than one element - в определённых случаях требуется что бы коллекция состояла как минимум из двух элементов (например при работе с рёбрами графа, где требуется указать две вершины графа, которые нужно связать)
* %s with ID = %d is not found - данные с указанным ID не обнаружены, где %s - может быть или NODE или EDGE, %d - номер id'шника.

*Сообщения об ошибках, возникающие при работе с рёбрами графа*

* Edge for nodes [%s, %s] is not found - ребро для указанных вершин (нод) не найдено, [%s, %s] - уникальные имена пары вершин.
* Edge for nodes ([%s, %s], [%s, %s]) already present in the graph - данное сообщение возникает при попытки добавить в граф уже существующее ребро. Где ([%s, %s], [%s, %s]) - подставляются уникальные имена вершин графа. Так как граф неориентированный, то например v1 и v2 <=> v2 и v1.
* Edges for node %s is not found - данное сообщение возникает при попытки извлечь информацию по рёбрам графа для заданной вершины, %s - уникальное имя вершины графа.

*Сообщения об ошибках, возникающие при работе с вершинами (нодами) графа*

* Node %s already present in the graph - данное сообщение возникает, при попытки добавить вершину, которая уже присутствует в графе.
* Error while update node with id = - сообщение возникает при неудачной попытки обновить данные по вершине графа, где id - номер идентификатора вершины.
* Node with NAME = %s is not found - сообщение возникает, при неудачном поиске вершины графа по её уникальному имени.
* Node %s is not found - сообщение возникает, при неудачном поиске вершины графа в режиме поиска по заданному объекту.
* Nodes %s and %s are not reachable to each other - сообщение возникает если один из узлов (вершин графа) не достижим до другого узла (т.е. имеются промежуточные узлы).
* Node %s is fault - сообщение возникает в случае генерации сбоя в узле (в вершине графа), т.е. узел оказался недоступным во время обхода по узлам.

[[rest-api-usage]]
= REST API

Далее - описание отдельных частей API REST-сервиса.

[[rest-api-usage-graph]]
== GRAPH API

Набор запросов при работе с графом в целом.

include::graph.adoc[]