stages:
  - compile
  - test
  - deploy

compile:
  stage: compile
  tags:
    - compile
    - maven

  script:
    - echo "Run compile stage with maven"
    - mvn compile

test:
  stage: test
  tags:
    - test
    - maven

  script:
    - echo "Run junit testing with maven"
    - mvn test

deploy:
  stage: deploy
  tags:
    - deploy
    - maven

  script:
    - echo "Packing into an executable jar file using maven and deploy"
    - mvn package
    - "rm -r -d -f lnkchkr/"
    - "mkdir -p lnkchkr"
    - "cp target/linkchecker-*.jar lnkchkr/linkchecker.jar"
    - "cp linkchecker_linux.sh lnkchkr/linkchecker_linux.sh"
    - "cp linkchecker_win.bat lnkchkr/linkchecker_win.bat"
    - "ls -l"

  artifacts:
    name: "linkchecker-$CI_COMMIT_REF_NAME"
    expire_in: 1 week
    paths:
      - lnkchkr/
