stages:
  - clean
  - compile
  - test
  - package
  - deploy

clean:
  stage: clean

  tags:
    - maven

  script:
    - echo "Clean old target data with maven"
    - mvn clean

compile:
  stage: compile
  tags:
    - compile
    - maven

  script:
    - echo "Run compile stage with maven"
    - mvn compile

test:
  stage: test
  tags:
    - test
    - maven

  script:
    - echo "Run junit testing with maven"
    - mvn test

package:
  stage: package
  tags:
    - package
    - maven

  script:
    - echo "Packing into an executable jar file using maven"
    - mvn package
    - "cp target/linkchecker-*.jar linkchecker.jar"

deploy:
  stage: deploy
  tags:
    - deploy

  script:
    - echo "Deploy"
    - "rm -r -d -f lnkchkr/"
    - "mkdir -p lnkchkr"
    - "mv linkchecker.jar lnkchkr/linkchecker.jar"
    - "cp linkchecker_linux.sh lnkchkr/linkchecker_linux.sh"
    - "cp linkchecker_win.bat lnkchkr/linkchecker_win.bat"
    - "ls -l"

  artifacts:
    name: "linkchecker-$CI_COMMIT_REF_NAME"
    expire_in: 1 week
    paths:
      - lnkchkr/
