stages:
  - clean
  - compile
  - test
  - package

clean:
  stage: clean

  tags:
    - maven

  script:
    - echo "Clean old target data with maven"
    - mvn clean

compile:
  stage: compile
  tags:
    - compile
    - maven

  script:
    - echo "Run compile stage with maven"
    - mvn compile

test:
  stage: test
  tags:
    - test
    - maven

  script:
    - echo "Run junit testing with maven"
    - mvn test

package:
  stage: package
  tags:
    - package
    - maven

  script:
    - echo "Packing into an executable jar file using maven"
    - mvn package
    - "rm -r -d -f lnkchkr/"
    - "mkdir -p lnkchkr"
    - "cp target/linkchecker-0.1.0.jar lnkchkr/linkchecker.jar"
    - "cp linkchecker_linux.sh lnkchkr/linkchecker_linux.sh"
    - "cp linkchecker_win.bat lnkchkr/linkchecker_win.bat"
    - "ls -l"

  artifacts:
    paths:
      - lnkchkr/
