stages:
  - clean
  - compile
  - test
  - package

clean:
  stage: clean

  tags:
    - maven

  script:
    - echo "Clean old target data with maven"
    - mvn clean

compile:
  stage: compile
  tags:
    - compile
    - maven

  script:
    - echo "Run compile stage with maven"
    - mvn compile

test:
  stage: test
  tags:
    - test
    - maven

  script:
    - echo "Run junit testing with maven"
    - mvn test

package:
  stage: package
  tags:
    - package
    - maven

  script:
    - echo "Packing into an executable jar file using maven"
    - mvn package
    - "rm -r -d -f lnkchkr/"
    - "mkdir -p lnkchkr"
    - "cp target/linkchecker-0.1.0.jar lnkchkr/linkchecker.jar"
    - "touch lnkchkr/application-production.properties"
    - "echo \"LINKCHECKER_PGSQL_DB_HOST=\" >> lnkchkr/application-production.properties"
    - "echo \"LINKCHECKER_PGSQL_DB_PORT=\" >> lnkchkr/application-production.properties"
    - "echo \"LINKCHECKER_PGSQL_DB_NAME=\" >> lnkchkr/application-production.properties"
    - "echo \"LINKCHECKER_PGSQL_DB_USER=\" >> lnkchkr/application-production.properties"
    - "echo \"LINKCHECKER_PGSQL_DB_PASSWORD=\" >> lnkchkr/application-production.properties"
    - "touch lnkchkr/linkchecker_win_demo.bat"
    - "touch lnkchkr/linkchecker_win_demo_debug.bat"
    - "touch lnkchkr/linkchecker_win_production.bat"
    - "touch lnkchkr/linkchecker_win_production_debug.bat"
    - "echo \"java -jar linkchecker.jar\" >> lnkchkr/linkchecker_win_demo.bat"
    - "echo \"java -jar linkchecker.jar --spring.profiles.active=demo,debug\" >> lnkchkr/linkchecker_win_demo_debug.bat"
    - "echo \"java -jar linkchecker.jar --spring.profiles.active=production\" >> lnkchkr/linkchecker_win_production.bat"
    - "echo \"java -jar linkchecker.jar --spring.profiles.active=production,debug\" >> lnkchkr/linkchecker_win_production_debug.bat"
    - "touch lnkchkr/linkchecker_linux_demo.sh"
    - "touch lnkchkr/linkchecker_linux_demo_debug.sh"
    - "touch lnkchkr/linkchecker_linux_production.sh"
    - "touch lnkchkr/linkchecker_linux_production_debug.sh"
    - "echo \"#!/bin/bash\" >> lnkchkr/linkchecker_linux_demo.sh"
    - "echo \"java -jar linkchecker.jar\" >> lnkchkr/linkchecker_linux_demo.sh"
    - "echo \"#!/bin/bash\" >> lnkchkr/linkchecker_linux_demo_debug.sh"
    - "echo \"java -jar linkchecker.jar --spring.profiles.active=demo,debug\" >> lnkchkr/linkchecker_linux_demo_debug.sh"
    - "echo \"#!/bin/bash\" >> lnkchkr/linkchecker_linux_production.sh"
    - "echo \"java -jar linkchecker.jar\" >> lnkchkr/linkchecker_linux_production.sh"
    - "echo \"#!/bin/bash\" >> lnkchkr/linkchecker_linux_production_debug.sh"
    - "echo \"java -jar linkchecker.jar --spring.profiles.active=demo,debug\" >> lnkchkr/linkchecker_linux_production_debug.sh"
    - "chmod +x -R lnkchkr/linkchecker_linux_production_debug.sh lnkchkr/linkchecker_linux_production.sh lnkchkr/linkchecker_linux_demo_debug.sh lnkchkr/linkchecker_linux_demo.sh"
    - "ls -l"

  artifacts:
    paths:
      - lnkchkr/
