spring:
  profiles:
    active: test, debug
logging:
  level:
    ru.resprojects: info
---
spring:
  profiles: production
  jpa:
    database: postgresql
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
  datasource:
    url: ${LINKCHECKER_PGSQL_DB_HOST}:${LINKCHECKER_PGSQL_DB_PORT}/${LINKCHECKER_PGSQL_DB_NAME}
    username: ${LINKCHECKER_PGSQL_DB_USER}
    password: ${LINKCHECKER_PGSQL_DB_PASSWORD}
    platform: postgresql
    initialization-mode: never
---
spring:
  profiles: demo, test
  jpa:
    database: h2
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:linkchecker;DB_CLOSE_ON_EXIT=FALSE
    initialization-mode: always
    platform: h2
---
spring:
  profiles: test
  thymeleaf:
    cache: false
---
spring:
  profiles: debug
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
logging:
  level:
    ru.resprojects: debug
---
spring:
  profiles: moc_test
---
spring:
  profiles: demo, production, test
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
---
spring:
  http:
    converters:
      preferred-json-mapper: gson
  output:
    ansi:
      enabled: detect

logging:
  level:
    org.springframework: error
  pattern:
    file: "%d %p %c{1.} [%t] %m%n"
    console: "%clr(%d{HH:mm:ss.SSS}){yellow} %clr(%-5p) %clr(---){faint} %clr([%t]){cyan} %clr(%logger{36}){blue} %clr(:){red} %clr(%msg){faint}%n"
  file:
    name: linkchecker.log
    max-size: 5MB

appmsg:
  app-msg:
    MSG_ARGUMENT_NULL: "Argument must not be null"
    MSG_COLLECTION_EMPTY: "Collection must not be empty"
    MSG_COLLECTION_CONTAIN_NULL: "Collection must not contain a null item"
    MSG_COLLECTION_CONTAIN_ONE_ELEMENT: "Collection must have more than one element"
    MSG_BY_ID_ERROR: "%s with ID = %d is not found"
  edge-msg:
    EDGE_MSG_GET_ERROR: "Edge for nodes [%s, %s] is not found"
    EDGE_MSG_ALREADY_PRESENT_ERROR: "Edge for nodes ([%s, %s], [%s, %s]) already present in the graph"
    EDGE_MSG_GET_BY_NAME_ERROR: "Edges for node %s is not found"
  node-msg:
    NODE_MSG_ALREADY_PRESENT_ERROR: "Node %s already present in the graph"
    NODE_MSG_UPDATE_ERROR: "Error while update node with id = "
    NODE_MSG_BY_NAME_ERROR: "Node with NAME = %s is not found"
    NODE_MSG_BY_OBJECT_ERROR: "Node %s is not found"
    NODE_MSG_NOT_REACHABLE: "Nodes %s and %s are not reachable to each other"
    NODE_MSG_IS_FAULT: "Node %s is fault"