spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  jpa:
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://192.168.20.234:5432/linkchecker
    username: user
    password: password
    platform: postgresql
    initialization-mode: always
---
spring:
  profiles: test
  jpa:
    show-sql: true
    database: h2
    open-in-view: false
  datasource:
    url: jdbc:h2:mem:linkchecker
    initialization-mode: always
    platform: h2

