spring:
  profiles:
    active: dev
---
spring:
  profiles: prod
  jpa:
    show-sql: false
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://192.168.20.234:5432/linkchecker
    username: user
    password: password
    platform: postgresql
    initialization-mode: never
---
spring:
  profiles: dev
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        generate_statistics: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://192.168.20.234:5432/linkchecker
    username: user
    password: password
    platform: postgresql
    initialization-mode: always
---
spring:
  profiles: test
  jpa:
    show-sql: true
    database: h2
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    url: jdbc:h2:mem:linkchecker;DB_CLOSE_ON_EXIT=FALSE
    initialization-mode: always
    platform: h2
---

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
  output:
    ansi:
      enabled: always

logging:
  level:
    org.springframework: error
    ru.resprojects: debug
  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
    console: "%clr(%d{HH:mm:ss.SSS}){yellow} %clr(%-5p) %clr(---){faint} %clr([%t]){cyan} %clr(%logger{36}){blue} %clr(:){red} %clr(%msg){faint}%n"
  file: app.log